name: AlchimiaVitae
author: Apeiros-46B
description: Slimefun addon that adds alchemy, herbalism, and a little magic
main: me.apeiros.alchimiavitae.AlchimiaVitae
version: ${version}
api-version: '1.21'
depend:
  - Slimefun
